Repository shravan20/github-readme-quotes, pull requests merged in 2020-11, with the labels that each got.

#7 Svg template for different themes
  src/api/controllers/quotesController.js
Labels: enhancement, help wanted

#11 [quote card designed] feature #015 card design added and fixed
  src/api/controllers/quotesController.js
  src/utils/cardTemplate.js
Labels: enhancement

#20 [Template] refactor Added Template class and refactored generateTemplate
  src/api/controllers/quotesController.js
  src/common/getTemplate.js
  src/models/Template.js
  src/utils/generateTemplate.js
Labels: enhancement

#31 Contribution
  CONTRIBUTING.md
Labels: documentation, enhancement

#32 Development
  CONTRIBUTING.md
  package-lock.json
  package.json
  test/unit/src/models/Template.js
  test/unit/src/utils/fetchApi.spec.js
Labels: documentation, enhancement, help wanted

#44 Updated README
  README.md
Labels: documentation, enhancement

#52 Development
  src/themes/README.md
Labels: documentation, enhancement

#62 Added services for quotes generator
  src/api/controllers/quotesController.js
  src/api/routes/quotes-router.js
  src/api/services/quotesService.js
  src/models/Template.js
Labels: enhancement

#63 [refactoring enhanced] fix | services layer division fixed
  src/api/controllers/quotesController.js
  src/api/services/quotesService.js
Labels: bug, enhancement

#64 Development
  src/api/controllers/quotesController.js
  src/api/routes/quotes-router.js
  src/api/services/quotesService.js
  src/models/Template.js
Labels: bug, enhancement

#65 Refactored theme key names
  src/layouts/layout.js
  src/themes/themes.js
Labels: enhancement, good first issue

#67 Added churchill layout
  src/layouts/layout.js
Labels: enhancement

#68 Development
  src/layouts/layout.js
Labels: enhancement

#72 Development
  src/layouts/layout.js
Labels: enhancement

#77 Development
  .github/workflows/greetings.yml
Labels: enhancement, good first issue
