Repository shravan20/github-readme-quotes, pull requests merged in 2020-12, with the labels that each got.

#81 Custom quotes
  README.md
  customQuotes/quotes.json
  src/api/controllers/quotesController.js
  src/api/services/quotesService.js
  src/utils/validateUrl.js
Labels: Medium work, enhancement, good first issue

#88 Svg height issue fix
  .gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/components/App/App.css
  frontend/src/components/App/App.js
  frontend/src/components/App/App.test.js
  frontend/src/components/Dashboard/index.js
  frontend/src/components/Pages/Home/index.js
  frontend/src/components/organisms/TemplateCard/index.js
  frontend/src/config/cardTemplate/index.js
  frontend/src/config/constants/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  package-lock.json
  src/api/services/quotesService.js
  src/app.js
  src/common/getTemplate.js
  src/layouts/layout.js
  src/models/Template.js
  src/utils/generateTemplate.js
Labels: Little work, bug, good first issue

#90 Dynamic height calculation for svg. Closes #87
  src/api/services/quotesService.js
  src/app.js
  src/common/getTemplate.js
  src/layouts/layout.js
  src/models/Template.js
  src/utils/generateTemplate.js
Labels: bug, good first issue

#91 Feature/category feature
  customQuotes/category.json
  src/api/controllers/quotesController.js
  src/api/services/quotesService.js
Labels: Little work, enhancement, good first issue

#92 Added quotes for motivational and fun category
  customQuotes/category.json
Labels: enhancement

#93 Added life,success,general,programming categories for custom quotes
  customQuotes/category.json
Labels: enhancement

#94 Documentation/version1.1
  CONTRIBUTING.md
  README.md
Labels: Little work, documentation, enhancement

#95 Create label.yml
  .github/workflows/label.yml
Labels: Little work, enhancement, good first issue

#96 Update README.md
  README.md
Labels: Little work, documentation, refactoring

#82 Development | Custom Quotes Feature extracting from Github Gists
  .github/workflows/label.yml
  CONTRIBUTING.md
  README.md
  customQuotes/category.json
  customQuotes/quotes.json
  src/api/controllers/quotesController.js
  src/api/services/quotesService.js
  src/app.js
  src/common/getTemplate.js
  src/layouts/layout.js
  src/models/Template.js
  src/utils/generateTemplate.js
  src/utils/validateUrl.js
Labels: Little work, enhancement, good first issue

#97 Readme update
  README.md
Labels: bug, documentation

#99 Update README.md
  README.md
Labels: documentation

#100 [FRONTEND] Preview quotes and generate URL
  .gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/public/apple-touch-icon.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/components/App/App.css
  frontend/src/components/App/App.js
  frontend/src/components/App/App.test.js
  frontend/src/components/Dashboard/index.js
  frontend/src/components/Pages/Home/index.js
  frontend/src/components/organisms/TemplateCard/index.js
  frontend/src/config/cardTemplate/index.js
  frontend/src/config/constants/index.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
  frontend/src/util/animation/index.js
  frontend/src/util/layouts/index.js
  frontend/src/util/template/Template.js
  frontend/src/util/template/getTemplate.js
  frontend/src/util/themes/index.js
Labels: Much work, enhancement, help wanted

#106 Copy button issue fix.Closes #104
  README.md
Labels: bug
