Repository shravan20/github-readme-quotes, pull requests merged in 2021-04, with the labels that each got.

#121 #120 Adds custom Theming Functionality, and Dark Theme toggle Logic.
  frontend/src/components/Dashboard/index.js
  frontend/src/moon.svg
  frontend/src/sun.svg
  frontend/src/util/styles/componentStyles.js
  frontend/src/util/themes/GlobalThemes.js
Labels: Medium work, documentation, enhancement, good first issue, help wanted

#125 Thank you contributors
  frontend/src/components/Constants/urlConfig.js
  frontend/src/components/ContributorsCard/ContributorCard.js
  frontend/src/components/Pages/Home/index.js
Labels: Little work, enhancement, good first issue, help wanted

#129 fixed the alignment of zeus grid
  frontend/src/components/organisms/TemplateCard/index.js
Labels: Little work, bug, good first issue, help wanted
