Repository shravan20/github-readme-quotes, pull requests merged in 2023-10, with the labels that each got.

#246 Hotfix - Renamed createMuiTheme import into createTheme
  frontend/src/components/Dashboard/index.js
Labels: bug, refactoring, hacktoberfest-accepted, hacktoberfest, frontend

#227 My quote
  customQuotes/quotes.json
Labels: enhancement, help wanted, Little work, refactoring, hacktoberfest-accepted, hacktoberfest

#248 Hotfix - Dynamic url generation
  frontend/src/components/organisms/TemplateCard/index.js
Labels: bug, enhancement, help wanted, good first issue, Little work, hacktoberfest-accepted, hacktoberfest, frontend, backend

#247 Clean code - Refinement ContributorCard
  frontend/src/components/ContributorsCard/ContributorCard.js
Labels: bug, enhancement, help wanted, good first issue, Medium work, hacktoberfest-accepted, hacktoberfest, frontend

#252 Add discord logo in dashboard
  frontend/src/assets/discord_logo.png
  frontend/src/components/Dashboard/discord.js
  frontend/src/components/Dashboard/index.js
Labels: enhancement, help wanted, good first issue, Little work, hacktoberfest-accepted, hacktoberfest, frontend

#255 feat: Change style for discord | new category added
  customQuotes/category.json
  frontend/src/assets/discord_logo.png
  frontend/src/components/Dashboard/discord.js
Labels: good first issue, Little work, hacktoberfest-accepted, hacktoberfest, frontend

#257 Inclusion of new category Travel
  customQuotes/category.json
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#271 added a quotes
  customQuotes/category.json
Labels: enhancement, hacktoberfest

#272 Added Emojis in quotes and category.json
  customQuotes/category.json
  customQuotes/quotes.json
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#270 Added new quotes.json
  customQuotes/quotes.json
Labels: hacktoberfest-accepted, hacktoberfest

#267 Change layout width to 600px
  frontend/src/util/layouts/index.js
  src/api/controllers/quotesController.js
  src/layouts/layout.js
Labels: bug, enhancement, good first issue, Little work, refactoring, hacktoberfest
